Shader "Matej Vanco/Raymarcher/RaymarcherRenderer_RMSampleScene_Texes"
{
	// The shader was generated by the RMConvertor - Please do not change any properties nor location of the shader manually

	Properties
	{

	}
	SubShader
	{
		Tags { "RenderType"="Transparent" "Queue"="Transparent"}
        Cull Off ZWrite Off ZTest Always
        Blend SrcAlpha OneMinusSrcAlpha

		Pass
		{
HLSLPROGRAM

				#pragma vertex RMVertex
				#pragma fragment RMFragment
				#pragma target 3.5

				#define RAYMARCHER_PIPELINE_HDRP

				#ifndef RAYMARCHER_PIPELINE_HDRP
					#include "UnityCG.cginc"
				#else
					#include "Packages\com.unity.render-pipelines.core\ShaderLibrary\Common.hlsl"
					#include "Packages\com.unity.render-pipelines.high-definition\Runtime\ShaderLibrary\ShaderVariables.hlsl"
				#endif

				#define RAYMARCHER_TYPE_QUALITY

				#pragma shader_feature_fragment ITERATIONSx16 ITERATIONSx32 ITERATIONSx64 ITERATIONSx128 ITERATIONSx256 ITERATIONSx512
				#ifdef ITERATIONSx16
					#define RAYMARCHER_ITERATIONS 16
				#elif ITERATIONSx32
					#define RAYMARCHER_ITERATIONS 32
				#elif ITERATIONSx64
					#define RAYMARCHER_ITERATIONS 64
				#elif ITERATIONSx512
					#define RAYMARCHER_ITERATIONS 512
				#elif ITERATIONSx256
					#define RAYMARCHER_ITERATIONS 256
				#else
					#define RAYMARCHER_ITERATIONS 128
				#endif

				#pragma shader_feature_fragment RAYMARCHER_MAIN_LIGHT
				#pragma shader_feature_fragment RAYMARCHER_ADDITIONAL_LIGHTS
// No additional lights detected. RAYMARCHER_LIGHT_COUNT has been removed

				#pragma shader_feature_fragment RAYMARCHER_SCENE_DEPTH
				#pragma shader_feature_fragment RAYMARCHER_SMOOTH_BLEND
				#pragma shader_feature_fragment RAYMARCHER_REACT_GEOMETRY
				#pragma shader_feature_fragment RAYMARCHER_DISTANCE_FOG
				#pragma shader_feature_fragment RAYMARCHER_PIXELATION

				#include "..\..\CoreLibrary\RMHLSL_Input.cginc"

				#include "..\..\CoreLibrary\RMHLSL_Common.cginc"

				#include "..\SdfObjectBuffers\RM_SdfObjectBuffer_RMSampleScene_Texes.cginc"

				#include "..\..\CoreLibrary\RMHLSL_RayHit.cginc"

				#include "..\MaterialBuffers\RM_MaterialBuffer_RMSampleScene_Texes.cginc"

				#include "..\..\CoreLibrary\RMHLSL_RenderBase.cginc"

				#include "..\..\CoreLibrary\RMHLSL_FragVert.cginc"

ENDHLSL
		}
	}
}
